[postgres]
host=
port=5432
dbname=
user=
password=

[target]
schema=_6_hechos
table=converge_esc_encuesta_satisf_cli

[target_defensa_options]
1=proyecto_dashboard_defensa.converge_proyectos_financieros
2=proyecto_dashboard_defensa.converge_dopd_riesgos

[input]
# Carpeta de entrada de excels
input_dir=./inputs
# Carpeta para reintentos (normalmente donde se corrigen inválidos)
retry_input_dir=./inputs_retry
# Vacío = toma el último excel modificado
file_name=
# Hoja de excel a procesar
sheet_name=bbdd
header_row = 5

[output]
output_dir=./salidas
# mapping.ini persistente (puede ser ruta absoluta o relativa al script)
mapping_file=mapping.ini
# Índice json para correlacionar parciales/reintentos
retry_index_file=retry_index.json
# Gestión del excel tras carga completa/parcial: none|move|rename
processed_mode=move
# Si processed_mode=move, carpeta destino
processed_dir=./excels_done
# Si processed_mode=rename, sufijo base agregado al nombre
loaded_suffix=_LOADED[output]
cleanup_mapping_review=true

[run]
batch_size=1000
progress_every=10000
min_year=1900
max_year=2100
# Umbral de similitud (0-1) para mapear columnas excel -> tabla por texto
similarity_threshold=0.78
auto_confirm_known_mapping=true

[fixed_values]
# Tokens especiales soportados:
# __now_ts__, __today__, __true__, __false__, __null__
fecha_carga=__now_ts__
fecha_creacion=__today__
fecha_ult_modificacion=__today__
creador=Massive Import
ult_modificador=Massive Import
deleted_row=__false__

[column_map]
# Opcional: mapeos manuales adicionales Excel -> columna destino
# operacion cdg=operacion_cdg
# id=id_externo

[import_actions]
# Sección opcional para definir acciones previas antes del insert masivo.
# Clave = nombre de la sección destino (schema.tabla sin puntos o con puntos)
# valor = SQL simple a ejecutar (ej. TRUNCATE tabla, DELETE FROM ... WHERE ...)
# Si la tabla no está aquí, se asume que no requiere acción previa.
# Ejemplo para tabla DopD:
# converge_dopd_riesgos = TRUNCATE CONCURRENTLY PROYECTO_DASHBOARD_DEFENSA.converge_dopd_riesgos;
proyecto_dashboard_defensa.converge_dopd_riesgos = TRUNCATE TABLE proyecto_dashboard_defensa.converge_dopd_riesgos;